# Generated by Django 5.2.9 on 2025-12-03 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog_post',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
