# Generated by Django 5.2.9 on 2025-12-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_description_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user__username'], 'verbose_name': 'Blogger', 'verbose_name_plural': 'Bloggers'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='posted_date',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='posted_date',
            new_name='post_date',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='name',
        ),
    ]
